### ISSUE TITLE
Feature request: Converter for DosBoxPure

### ISSUE THREAD

**Issue by toniosj** [Voljega/ExoDOSConverter#103]
DosBoxPure uses .zip files and inside a file "dosbox.bat" with all dosbox config.

**Comment by Voljega** [comment]
Dosbox Pure was made by a self described very smart man who claimed he could simplify dosbox games usage by getting rid of dosbox.bat and dosbox.conf.

Everyone knlowledgable in dosbox kept telling him it was not possible but he refused to hear it.

So he released his thing, which is twice more broken than any dosbox core out here, and since then he's desperately been trying to get to the same level of working functionalities than the other cores, ultimately having to put back dosbox.bat and cfg in there in a way much more complicated than the regular basic usage which has been in use for the past decade.

Beside that, zip format is useless and bothersome as soon as the game uses CD or has big files.

In the end, dosbox pure is more complicated to use than other cores and doesn't bring anything remotely interesting to the table

SI no, I won't be supporting dosbox pure.

**Comment by toniosj** [comment]
Hi! On last DosBOX-Pure beta, full compatibility with dosbox.conf files has been added.

It works fine now with game uses CD or has big files.

**Comment by Torinde** [comment]
I ask about comparison between those and list what difference I found at schellingb/dosbox-pure/issues/364

**Comment by Voljega** [comment]
On Batocera, the converter works now fine with lr-dosbox-pure provided you disable dosbox-pure automapping (strike scroll lock on your keyboard while ingame)

I must say the emulator is now pretty good, if you use it as a regular dosbox core, especially on the performance side

**Comment by chr0m** [comment]
Best way to use this to make games for dosbox pure on an RG35XX?

**Comment by Voljega** [comment]
@chr0m can you open a fresh issue about dosbox pure on RG35XX ?

**Comment by toniosj** [comment]
Good feaure would be, add "Dosbox Pure" export

ExoDosvoncerter generates .zip file with dosbox.conf file (dosbos.cfg+dosbox.bat) (BATOCERA MODE)

I have created my own dosboxpure pack using Batocera export, but adding my personal process:

1) I mix dosbos.cfg+dosbox.bat in a dosbox.conf file
2) I delete dosbos.cfg+dosbox.bat
3) I convert game.pc folder, to game.pc.zip file
4) I change filename game.pc.zip to game.zip

And then dosbox-pure runs the game automatically using dosbox.conf inside zipfile.

**Comment by Voljega** [comment]
How does it works with iso / bin / etc inside the zip ?
Wouldn't it be extra slow ?

**Comment by toniosj** [comment]
How does it works with iso / bin / etc inside the zip ? YES!

Wouldn't it be extra slow ? No, I play games like Alone In the Dark, MegaRace2, MDK .... with ISOs inside and I have no slowdowns.

**Comment by toniosj** [comment]
I use this structure:

Alone in the Dark.zip
-adark1 (folder)
--cd (folder)
---alonein.bin
---alonein.cue
--DARK (folder)
--- ........
-dosbox.conf


dosbox.conf file:
**# Config file for Dosbox-0.74
[sdl]
fullscreen=true
fulldouble=false
fullresolution=desktop
windowresolution=1280x960
output=texture
renderer=auto
vsync=false
mapperfile=mapper.map
[dosbox]
machine=svga_s3
memsize=32
[render]
aspect=true
scaler=normal2x
[cpu]
core=auto
cycles=8000
cycleup=500
[mixer]
blocksize=2048
prebuffer=10
[midi]
[sblaster]
[gus]
gus=true
[speaker]
[joystick]
buttonwrap=false
[serial]
[dos]
keyboardlayout=none
[ipx]
[autoexec]
imgmount d .\adark1\cd\alonein.cue -t cdrom
c:
cd adark1
cd DARK
cd INDARK
INDARK**

**Comment by Voljega** [comment]
I see, so you compress the files inside adark1.pc but not adark1.pc folder
itself ?

**Comment by Voljega** [comment]
@toniosj I created the following dedicated issue for this enhancement, please continue the discussion here: https://github.com/Voljega/ExoDOSConverter/issues/113
