### ISSUE TITLE
EmuELEC conversion does not work

### ISSUE THREAD

**Issue by pablosanjose** [Voljega/ExoDOSConverter#77]
There are several issues with the EmuELEC conversion
- the game folders in `pcdata` are not grouped by genre (they are in the `pc` folder), so mount fails
- the frontend requires an empty `gamename.bat` to be created in each game folder. Otherwise games are not listed in the UI
- the script `/emuelec/scripts/emuelecRunEmu.sh` must be modified to read the exported configuration files (need to comment/uncomment the relevant `RUNTHIS` commands). This is probably not the task of ExoDOSConverter, but the user should be instructed about this change more clearly
- scripts sometimes refer to game folders as `gamename.pc` and other times as `gamename`, which leads to mount failures (example: eye of the beholder II)

**Comment by Voljega** [comment]
Hello, thank you for this, I don't have any other user testing the EmuELEC conversion and my communications on their forum were downvoted as spam (?) so I can't say I tried too much to go back there...

I will look into this in the coming months ans use this issue to communciate about fixes

**Comment by Voljega** [comment]
Hello, I'm ready to work on this now
If you have Discord, can you contact me there @pablosanjose ?
Would be easier to discuss about it

**Comment by Voljega** [comment]
Or here is good too :p
Already fixed two of the issues, remaining :
- the frontend requires an empty gamename.bat to be created in each game folder. Otherwise games are not listed in the UI
- the script /emuelec/scripts/emuelecRunEmu.sh must be modified to read the exported configuration files (need to comment/uncomment the relevant RUNTHIS commands). This is probably not the task of ExoDOSConverter, but the user should be instructed about this change more clearly

**Comment by Voljega** [comment]
All shall be fixed, please comment if you think there are still issues with the fix or possible enhancements

**Comment by pablosanjose** [comment]
Hi @Voljega ,  sorry I didn't reply. I actually prefer to use GitHub. I'll try to clear some time this weekend to test your fixes and get back to you.

**Comment by Voljega** [comment]
No problem, thank you for testing

Le ven. 28 mai 2021 à 08:59, Pablo San-Jose ***@***.***> a
écrit :
