### ISSUE TITLE
Python 3.9 compatibilty

### ISSUE THREAD

**Issue by Voljega** [Voljega/ExoDOSConverter#83]
There might be an incompatibility with Python 9.
At least windows build through pyinstaller seems to show issues

Needs investigation

**Comment by flynnsbit** [comment]
I did a brand new install on my new machine, pycharm 2021.1.1, I did manually run 'pip install pillow' and 'pip install requests' to get a successful build. Just verifying that the very latest code on github does in fact build on a new installed machine.

I'll verify with Python 3.9 as well.

**Comment by Voljega** [comment]
Thanks for the investigation :)
I'm slowly resuming work to finish the mapping code before moving back to more interesting things

**Comment by flynnsbit** [comment]
3.9 builds as well.  I just needed pillow and requests through the pip installer.
`C:\GitHub\ExoDOSConverter>build
245 INFO: PyInstaller: 4.3
245 INFO: Python: 3.9.5
265 INFO: Platform: Windows-10-10.0.18363-SP0
265 INFO: wrote C:\GitHub\ExoDOSConverter\main.spec
278 INFO: UPX is not available.
278 INFO: Removing temporary files and cleaning cache in C:\Users\shawn\AppData\Local\pyinstaller
306 INFO: Extending PYTHONPATH with paths
['C:\\GitHub\\ExoDOSConverter', 'C:\\GitHub\\ExoDOSConverter']
490 INFO: checking Analysis
490 INFO: Building Analysis because Analysis-00.toc is non existent
490 INFO: Initializing module dependency graph...
490 INFO: Caching module graph hooks...
505 WARNING: Several hooks defined for module 'win32ctypes.core'. Please take care they do not conflict.
553 INFO: Analyzing base_library.zip ...
4423 INFO: Processing pre-find module path hook distutils from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
4431 INFO: distutils: retargeting to non-venv dir 'c:\\python\\lib'
8817 INFO: Caching module dependency graph...
8942 INFO: running Analysis Analysis-00.toc
8942 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\python\python.exe
8989 WARNING: lib not found: api-ms-win-core-path-l1-1-0.dll dependency of c:\python\python39.dll
8990 INFO: Analyzing C:\GitHub\ExoDOSConverter\main.py
9916 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
12418 INFO: Processing module hooks...
12426 INFO: Loading module hook 'hook-certifi.py' from 'c:\\python\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
12426 INFO: Loading module hook 'hook-difflib.py' from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
12434 INFO: Loading module hook 'hook-distutils.py' from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
12434 INFO: Loading module hook 'hook-distutils.util.py' from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
12434 INFO: Loading module hook 'hook-encodings.py' from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
12524 INFO: Loading module hook 'hook-heapq.py' from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
12524 INFO: Loading module hook 'hook-lib2to3.py' from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
12667 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
12676 INFO: Loading module hook 'hook-pickle.py' from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
12676 INFO: Loading module hook 'hook-PIL.Image.py' from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
13244 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
13244 INFO: Loading module hook 'hook-PIL.py' from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
13252 INFO: Import to be excluded not found: 'FixTk'
13252 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
13252 INFO: Import to be excluded not found: 'FixTk'
13252 INFO: Loading module hook 'hook-sysconfig.py' from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
13260 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
13260 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
13260 INFO: Loading module hook 'hook-xml.py' from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
13260 INFO: Loading module hook 'hook-_tkinter.py' from 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
13453 INFO: checking Tree
13453 INFO: Building Tree because Tree-00.toc is non existent
13453 INFO: Building Tree Tree-00.toc
13683 INFO: checking Tree
13683 INFO: Building Tree because Tree-01.toc is non existent
13698 INFO: Building Tree Tree-01.toc
13828 INFO: checking Tree
13828 INFO: Building Tree because Tree-02.toc is non existent
13828 INFO: Building Tree Tree-02.toc
13854 INFO: Looking for ctypes DLLs
13870 INFO: Analyzing run-time hooks ...
13870 INFO: Including run-time hook 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
13886 INFO: Including run-time hook 'c:\\python\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_certifi.py'
13886 INFO: Including run-time hook 'c:\\python\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
13913 INFO: Looking for dynamic libraries
14324 INFO: Looking for eggs
14324 INFO: Using Python library c:\python\python39.dll
14324 INFO: Found binding redirects:
[]
14348 INFO: Warnings written to C:\GitHub\ExoDOSConverter\build\main\warn-main.txt
14401 INFO: Graph cross-reference written to C:\GitHub\ExoDOSConverter\build\main\xref-main.html
14417 INFO: checking PYZ
14430 INFO: Building PYZ because PYZ-00.toc is non existent
14430 INFO: Building PYZ (ZlibArchive) C:\GitHub\ExoDOSConverter\build\main\PYZ-00.pyz
14988 INFO: Building PYZ (ZlibArchive) C:\GitHub\ExoDOSConverter\build\main\PYZ-00.pyz completed successfully.
15020 INFO: checking PKG
15020 INFO: Building PKG because PKG-00.toc is non existent
15020 INFO: Building PKG (CArchive) PKG-00.pkg
30104 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
30109 INFO: Bootloader c:\python\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
30109 INFO: checking EXE
30109 INFO: Building EXE because EXE-00.toc is non existent
30109 INFO: Building EXE from EXE-00.toc
30166 INFO: Copying icons from ['exodosicon.ico']
30367 INFO: Writing RT_GROUP_ICON 0 resource with 20 bytes
30367 INFO: Writing RT_ICON 1 resource with 165640 bytes
30383 INFO: Updating manifest in C:\GitHub\ExoDOSConverter\build\main\run.exe.si47fsx5
30524 INFO: Updating resource type 24 name 1 language 0
30524 INFO: Appending archive to EXE C:\GitHub\ExoDOSConverter\dist\main.exe
35367 INFO: Building EXE from EXE-00.toc completed successfully.
        1 file(s) copied.
`

**Comment by Voljega** [comment]
Nice ! Thanks I can can close this
